// packages/vue/src/App.vue
<script lang="ts" setup>
import { computed, ref } from "vue"

type Item = {
  value: string,
  done: boolean,
}

let items = ref<Item[]>([])
let undoneItems = computed(() => items.value.filter(i => !i.done))

let value = ref("")
let showFinished = ref(true)

const addItem = () => {
  if (value.value !== "" && value.value) {
    items.value.push({ value: value.value, done: false })
    value.value = ""
  }
}

const submitItem = (e: KeyboardEvent) => {
  if (e.key === "Enter") addItem()
}
</script>

<template>
  <h1>This was built with Vue!</h1>
  <input v-model="value" @keydown="submitItem">
  <button @click="addItem">Add</button>
  <input id="show-done" v-model="showFinished" type="checkbox">
  <label for="show-done">Show done</label>
  <ul>
    <li v-for="item in (showFinished ? items : undoneItems)"
        :class="{ done: item.done }"
        class="item"
        @click="() => item.done = !item.done"
    >
      {{ item.value }}
    </li>
  </ul>
</template>

// svelte/src/App.svelte
<script lang="ts">
	type Item = {
		value: string,
		done: boolean,
	}

	export let items: Item[] = []
	$: undoneItems = items.filter(i => !i.done)

	let value: string
	let showFinished = true

	const addItem = () => {
		if (value !== "" && value) {
			items = [{ value, done: false }, ...items]
			value = ""
		}
	}

	const submitItem = (e: KeyboardEvent) => {
		if (e.key === "Enter") addItem()
	}
</script>

<h1>This was built with Svelte!</h1>
<input bind:value on:keypress={submitItem}>
<button on:click={addItem}>Add</button>
<input bind:checked={showFinished} id="show-done" type="checkbox">
<label for="show-done">Show done</label>
<ul>
	{#each (showFinished ? items : undoneItems) as item}
		<li class="item" on:click={() => item.done = !item.done} class:done={item.done}>
			{item.value}
		</li>
	{/each}
</ul>
